import { mkdir, writeFile } from 'fs/promises';
import { createWriteStream, readFileSync } from 'fs';

import { IconNode, icons as lucideIcons } from 'lucide';

// read lucide.d.ts to find deprecated icons
const types = readFileSync('./node_modules/lucide/dist/lucide.d.ts', 'utf8');
const deprecatedIcons = new Set<string>();
const regex = /@deprecated[\s\S]*?declare const (\w+)/g;
let match;
while ((match = regex.exec(types))) deprecatedIcons.add(match[1]);

const globalProps = [
  'Infinity',
];

// remove duplicate icons and fix some icon names to avoid shadowing of global properties
const icons = Object.keys(lucideIcons).reduce((acc: Record<string, IconNode>, name) => {
  const icon = lucideIcons[name as keyof typeof lucideIcons];
  const duplicate = Object.values(acc).find(i => JSON.stringify(i) === JSON.stringify(icon));
  if (!duplicate) acc[name] = icon;

  if (globalProps.includes(name)) {
    const newName = `${name}Icon`;
    acc[newName] = icon;
    delete acc[name];
  }

  return acc;
}, {});

function buildContent(icon: IconNode) {
  const elements = icon.map(t => {
    const tag = t[0];
    const attrs = Object.entries(t[1]).map(v => `${v[0]}="${v[1]}"`).join(' ');
    return `<${tag} ${attrs}/>`;
  });

  return `${elements.join('')}`;
};

function buildIcon() {
  const baseIconPath = '../base-icon';
  const template = readFileSync('./icon.tsx.template', 'utf8')
    .replace('{{BASE_ICON_REL_PATH}}', baseIconPath);

  return function(name: string, content: string) {
    // add deprecation comment if the icon is deprecated in lucide
    const deprecated = deprecatedIcons.has(name)
      ? `/**
 * @deprecated Brand icons are deprecated in Lucide.
 * Use https://simpleicons.org instead.
 */`
      : '';
    
    return template
      .replace('{{DOCS}}', deprecated)
      .replace(/{{ICON_NAME}}/g, name)
      .replace('{{CONTENT}}', content);
  };
};

function buildExportLine(name: string, iconsRelPath: string) {
  return `export * from '${iconsRelPath}${name}';\n`;
}

async function build() {
  // build icons
  const iconsPath = './src/components/icons/';
  const build = buildIcon();

  await mkdir(iconsPath, { recursive: true });
  await Promise.all(Object.keys(icons).map(name => {
    const icon = icons[name];

    return writeFile(`${iconsPath}${name}.tsx`, build(name, buildContent(icon)), 'utf8');
  }));

  // export icons
  const baseIconPath = './components/base-icon';
  const indexFile = createWriteStream('./src/index.ts', 'utf8');
  indexFile.write('// This file is auto-generated by build.ts\n');
  indexFile.write(`export * from '${baseIconPath}';\n\n`);
  Object.keys(icons).forEach(k => indexFile.write(buildExportLine(k, './components/icons/')));
  indexFile.close();
}

build();
